namespace FluidScript.Compiler
{
    public enum IdentifierType
    {
        Class,
        Public,
        Private,
        New,
        This,
        True,
        False,
        Null,
        Undefined,
        Return,
        Var,
        Const,
        Function,
        Lamda,
        If,
        Else,
        While,
        Do,
        For,
        Loop,
        Continue,
        Switch,
        Break,
        Throw
    }
}
